Fixed cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -13,44 +13,46 @@ steps:
 
         gcloud config set project mystical-sweep-439114-m6
     entrypoint: bash
-
-
-  # Step 2: Install Python dependencies
   - name: 'python:3.12'
-    entrypoint: 'bash'
     args:
       - '-c'
       - |
-        set -x  # Enable debug mode
-        pip install --upgrade pip || { echo 'Pip upgrade failed'; exit 1; }
-        pip install -r requirements.txt || { echo 'Installing requirements failed'; exit 1; }
-
-  # Step 3: Deploy Airflow DAGs to Cloud Composer GCS bucket
-  - name: 'gcr.io/cloud-builders/gsutil'
-    args: ['-m', 'cp', '-r', 'etl_airflow/dags/*', 'gs://us-central1-my-composer-env-1f9279c3-bucket/dags/']
-
-  # Step 4: Deploy the dbt project to GCS
-  - name: 'gcr.io/cloud-builders/gsutil'
-    args: ['-m', 'cp', '-r', 'dbt_project/*', 'gs://us-central1-my-composer-env-1f9279c3-bucket/data/dbt_project/']
-
-  # Step 5: Trigger the dbt models in Cloud Composer
-  - name: 'gcr.io/cloud-builders/gcloud'
+        pip install --upgrade pip
+        pip install -r requirements.txt
+    entrypoint: bash
+  - name: gcr.io/cloud-builders/gsutil
     args:
-      - 'composer'
-      - 'environments'
-      - 'run'
-      - 'my-composer-env'
-      - '--location'
-      - 'us-central1'
-      - 'trigger_dag'
-      - '--'
-      - 'snowflake_to_gcs_and_bigquery_with_dbt'
+      - '-m'
+      - cp
+      - '-r'
+      - etl_airflow/dags/*
+      - 'gs://us-central1-my-composer-env-1f9279c3-bucket/dags/'
+  - name: gcr.io/cloud-builders/gsutil
+    args:
+      - '-m'
+      - cp
+      - '-r'
+      - dbt_project/*
+      - 'gs://us-central1-my-composer-env-1f9279c3-bucket/data/dbt_project/'
+  - name: gcr.io/cloud-builders/gcloud
+    args:
+      - '-c'
+      - >
+        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST
+        "https://cde25881594a44e1b368145ca12feb2f-dot-us-central1.composer.googleusercontent.com/api/v1/dags/snowflake_to_gcs_and_bigquery_with_dbt/dagRuns"
+        \
+          -H "Content-Type: application/json" \
+          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
+          -d '{"conf": {}}')
+        echo "Response code: $response"
 
-substitutions:
-  _PROJECT_ID: 'mystical-sweep-439114-m6'
-  _SERVICE_ACCOUNT_KEY: '<base64-encoded-service-account-json>'
-  _COMPOSER_BUCKET_NAME: 'us-central1-my-composer-env-1f9279c3-bucket'
-  _COMPOSER_ENV_NAME: 'my-composer-env'
-
-# Optional: Notification if the build fails
+        if [ "$response" -ne 200 ]; then
+          echo "DAG trigger failed with response code: $response"
+          exit 1
+        else
+          echo "DAG triggered successfully."
+        fi
+    entrypoint: bash
 timeout: 1200s
+options:
+  logging: CLOUD_LOGGING_ONLY
